// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var MainLayout = require("./layouts/MainLayout.bs.js");
var Router = require("next/router");

var PageComponent = {};

function $$default(props) {
  var router = Router.useRouter();
  var content = React.createElement(props.Component, props.pageProps);
  var match = router.route;
  switch (match) {
    case "/examples" :
        return React.createElement(MainLayout.make, {
                    children: null
                  }, React.createElement("h1", {
                        className: "font-bold"
                      }, "Examples Section"), React.createElement("div", undefined, content));
    case "/register_user" :
        return React.createElement(MainLayout.make, {
                    children: React.createElement("h1", {
                          className: "font-bold"
                        }, React.createElement("div", undefined, content))
                  });
    default:
      return React.createElement(MainLayout.make, {
                  children: content
                });
  }
}

exports.PageComponent = PageComponent;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
