// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Login_userNamePasswordForm = require("./components/Login_userNamePasswordForm.bs.js");

function $$default(param) {
  return React.createElement("div", undefined, React.createElement(Login_userNamePasswordForm.make, {}));
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
