// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var NextI18next = require("next-i18next");

function ErrorMessage(Props) {
  var msgKey = Props.msgKey;
  var className = Props.className;
  var match = React.useState(function () {
        return false;
      });
  var setIsDisplayed = match[1];
  var isDisplayed = match[0];
  var match$1 = NextI18next.useTranslation();
  var t = match$1.t;
  var show = function (param) {
    if (isDisplayed) {
      return React.createElement("article", {
                  className: ""
                }, React.createElement("div", {
                      className: ""
                    }, React.createElement("button", {
                          "aria-label": "",
                          className: "",
                          onClick: (function (param) {
                              return Curry._1(setIsDisplayed, (function (param) {
                                            return false;
                                          }));
                            })
                        })), React.createElement("div", {
                      className: className
                    }, t(msgKey)));
    } else {
      return "";
    }
  };
  return React.createElement("div", undefined, show(undefined));
}

var make = ErrorMessage;

exports.make = make;
/* react Not a pure module */
