// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function FormFieldError(Props) {
  var msg = Props.msg;
  return React.createElement("span", {
              className: "has-text-danger"
            }, msg);
}

var make = FormFieldError;

exports.make = make;
/* react Not a pure module */
