// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Hello(Props) {
  return React.createElement("div", undefined, "Hello hello hello!");
}

var make = Hello;

exports.make = make;
/* react Not a pure module */
