// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Link = require("next/link").default;

function MainLayout$Navigation(Props) {
  return React.createElement("nav", {
              className: "p-2 h-12 flex border-b border-gray-200 justify-between items-center text-sm"
            }, React.createElement("div", {
                  className: "flex w-2/3 justify-end"
                }, React.createElement(Link, {
                      href: "/",
                      children: React.createElement("a", {
                            className: "px-3"
                          }, "Home")
                    }), React.createElement(Link, {
                      href: "/examples",
                      children: React.createElement("a", {
                            className: "px-3"
                          }, "Examples")
                    }), React.createElement(Link, {
                      href: "/register_user",
                      children: React.createElement("a", {
                            className: "px-3"
                          }, "Register")
                    }), React.createElement("a", {
                      className: "px-3 font-bold",
                      href: "https://github.com/ryyppy/nextjs-default",
                      target: "_blank"
                    }, "Github")));
}

var Navigation = {
  make: MainLayout$Navigation
};

function MainLayout(Props) {
  var children = Props.children;
  var minWidth = {
    minWidth: "20rem"
  };
  return React.createElement("div", {
              className: "flex lg:justify-center",
              style: minWidth
            }, React.createElement("div", {
                  className: "max-w-5xl w-full lg:w-3/4 text-gray-900 font-base"
                }, React.createElement(MainLayout$Navigation, {}), React.createElement("main", {
                      className: "mt-4 mx-4"
                    }, children)));
}

var Link$1;

var make = MainLayout;

exports.Link = Link$1;
exports.Navigation = Navigation;
exports.make = make;
/* react Not a pure module */
