// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Link = require("next/link").default;

function MainLayout$Navigation(Props) {
  return React.createElement("nav", {
              className: "flex ext-sm text-black flex-col items-center md:flex-row md:justify-around lg:justify-end bg-gray-100"
            }, React.createElement("div", {
                  className: "hover:bg-gray-400 md:hover:bg-transparent md:border-b-4 border-transparent md:hover:border-gray-700 h-14 flex items-center justify-center w-full md:w-auto"
                }, React.createElement(Link, {
                      href: "/",
                      children: React.createElement("a", {
                            className: "mx-3"
                          }, "Home")
                    })), React.createElement("div", {
                  className: "hover:bg-gray-400 md:hover:bg-transparent md:border-b-4 border-transparent md:hover:border-gray-700 h-14 flex items-center justify-center w-full md:w-auto"
                }, React.createElement(Link, {
                      href: "/examples",
                      children: React.createElement("a", {
                            className: "mx-3"
                          }, "Examples")
                    })), React.createElement("div", {
                  className: "hover:bg-gray-400 md:hover:bg-transparent md:border-b-4 border-transparent md:hover:border-gray-700 h-14 flex items-center justify-center w-full md:w-auto"
                }, React.createElement(Link, {
                      href: "/register_user",
                      children: React.createElement("a", {
                            className: "mx-3"
                          }, "Register")
                    })));
}

var Navigation = {
  make: MainLayout$Navigation
};

function MainLayout(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "flex lg:justify-center"
            }, React.createElement("div", {
                  className: "w-full text-gray-900 font-base"
                }, React.createElement(MainLayout$Navigation, {}), React.createElement("main", {
                      className: "md:mt-4 md:mx-4"
                    }, children)));
}

var Link$1;

var make = MainLayout;

exports.Link = Link$1;
exports.Navigation = Navigation;
exports.make = make;
/* react Not a pure module */
