// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function makeRegisterOptions(required, min, max, minLength, maxLength, pattern, param) {
  return {
          required: required,
          min: min,
          max: max,
          minLength: minLength,
          maxLength: maxLength,
          pattern: pattern
        };
}

var $$Error = {};

exports.makeRegisterOptions = makeRegisterOptions;
exports.$$Error = $$Error;
/* No side effect */
