// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("rescript/lib/js/caml_array.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

var Query = {};

var Client = {};

var User = {};

function testClient(client) {
  client.query("INSERT INTO users(name, email) VALUES($1, $2) RETURNING *", [
        "brianc",
        "brian.m.carlson@gmail.com"
      ], (function (err, res) {
          if (err !== undefined) {
            console.log(Caml_option.valFromOption(err).stack);
          } else {
            console.log(Caml_array.get(res.rows, 0).name);
          }
          
        }));
  
}

function makeConnectionOptions(host, port, database, user, password, param) {
  return {
          host: host,
          port: port,
          database: database,
          user: user,
          password: password
        };
}

var Pool = {
  makeConnectionOptions: makeConnectionOptions
};

exports.Query = Query;
exports.Client = Client;
exports.User = User;
exports.testClient = testClient;
exports.Pool = Pool;
/* No side effect */
